# Generated by Django 2.2.7 on 2020-03-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=50)),
                ('continent', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('custom_users_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='userapi.Custom_User')),
            ],
        ),
    ]
